management:
  endpoints:
    web:
      exposure:
        include: httptrace,health
logging:
  level:
    org.springframework.web.filter.CommonsRequestLoggingFilter: DEBUG
    com.consdata.kouncil: DEBUG
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
