language: java
jdk:
  - openjdk11
before_install:
  - nvm install v10.18.1
env:
  global:
    secure: F2vLP4HdrOGFXisduTRkOrKAvr3VnJ+G3AUaUaFvdvDmsW3SP97cQxesU4DVdDH1Z1jONnkIrVrh5xdw5MrY123dDteQ42VGxcGGAPmgjSxlKr/M4xAkv+CpbJRVrMIrwiiCS6ZUqkv1M8V3qt5n/b9OaRTHJ5BGJP6fh/WPn03qCmroP/zyqi2taLFZUWtvNxrg1FfThOx17sa8p5pNa4sxacnp3QJjEHWnt5PGs7Q8XGhYPevgD9Yvihj/8TDhoi7FWIXzmUufksmjzFirW/Bi6ltom6hsj4t7+dgHWpbkoSjDMLvHvfj6D+w87W0r/AZQ5Qt3hL9xi/lJH5VFYcZXwb8TdDY3COiEWQPF1FGK+6bqulFz1WavPGObC3AGIE6R6vbeTTQUSW46X81FlB4RSd8kyidqV5g8usqJJOUfkgDCxudS3jVe08JtbR69M15q7LlJM+YyAkCldFwYL9mLXLlZBFw0K6/fgL14/g99LLruNpXHZN2onrCdiWhMJ/0i5rPv2G5RHvK/6uESgNvO47oH5a3i5x59z0YOKwb7So1NcNrYcC4mgfAtG4LIB7BEuU/EHOep5E7KpEYsTbBEtLHJZZ3o/aS825Zf0z8zv8sGHiM85XU3eS5zRGJ81rcHSmiiE2tZq0iY9UNfrNJPYTgRHNa+lNNUEIj0HWY=
addons:
  sonarcloud:
    organization: "consdatacom"
    token:
      secure: QK8zcTZinLUnj3N60krqaAsuTjpsKdIZhjPlqO82qXjYsVacOmyucGSKVEzQCEG+G+qcCFZcRT+Xnpv4fVWxrXkqDh6wkjf2QLThx/hW0/nwOmJvd1Nq/xwbQSnPlQ8s1zvbc0XjURCNuvH7g9t59g/NrxF5hSLPm2kT8eZC079af7puebiHM0HxECmd6skqgWHBOJ1SgmuVYO75xluSrGjaX4DA/kJ1Lf0vh4ktRqGQeIrEOXWUgsufQbManeFKCMAroDWGWQSrXjbDlsTyrIKdvxPjWpQYVkTGqV4pJ6DEfLhf00/5gyDvNmV/TYc31IAQPoNfYzzKwxQYR5gAnFY5CXcoh/tuW9G2l38fqSNNrSrSYbqMjkhV4VE2GlxfymmB9e5X/eurp8b2BSqxBlk5t/EpasjtOpbKyQLMzoLApS6QPdcn/UGM23Uoz3DKLk0ObcU+lb4HeYemBV6F6pWr0b+mfg6ctrpCmkK9q8A9Hyh83mac6kUHVF36lyVEeRiD7bfyLw+PU7Ck00PX1lTXQrhfBIeVLV/dzil3I7rHH0aWCFztefVBH5jmvjl2Q2O07vtOx5gjdKXvFwYIbSE1hyvq0LWyRU0dL12yzH8bDRF4jujcV4zGP19EBkLqETMFOxA6f0QFCHYm6X7GWDLyy3Hu78pueKtZ+lRFDrI=
script:
  - mvn clean install sonar:sonar -Dsonar.projectKey=Consdata_kouncil
